import {
  chmodSync,
  createWriteStream,
  existsSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { spawn, type ChildProcess } from "node:child_process";
import { homedir, tmpdir } from "node:os";
import { dirname, join, resolve, sep } from "node:path";

import type { RuntimeHookPayload, RuntimeInstanceRecord } from "../../runtime-instance-store.js";
import type { RuntimeSourceClient } from "../../runtime-instance-store.js";
import { getOrgxPluginConfigDir } from "../../paths.js";
import type { CodexBinInfo } from "./autopilot-slice-utils.js";
import { normalizeCodexArgs } from "./autopilot-slice-utils.js";

type CreateAutopilotRuntimeDeps = {
  filename: string;
  autoContinueSliceChildren: Map<string, ChildProcess>;
  resolveByokEnvOverrides: () => Record<string, string | undefined>;
  safeErrorMessage: (err: unknown) => string;
  resolveCodexBinInfo: () => CodexBinInfo;
  upsertRuntimeInstanceFromHook: (
    payload: RuntimeHookPayload
  ) => RuntimeInstanceRecord;
  broadcastRuntimeSse: (
    event: string,
    payload: RuntimeInstanceRecord
  ) => void;
  clearSnapshotResponseCache: () => void;
};

export function createAutopilotRuntime(deps: CreateAutopilotRuntimeDeps) {
  function hasExplicitCodexSubcommand(args: string[]): boolean {
    const first = (args[0] ?? "").trim();
    if (!first || first.startsWith("-")) return false;
    return true;
  }

  function envFlag(name: string, defaultValue: boolean): boolean {
    const raw = (process.env[name] ?? "").trim().toLowerCase();
    if (!raw) return defaultValue;
    return !(raw === "0" || raw === "false" || raw === "no" || raw === "off");
  }

  function readFirstExisting(paths: string[]): string | null {
    for (const pathname of paths) {
      if (!pathname) continue;
      try {
        if (!existsSync(pathname)) continue;
        return readFileSync(pathname, "utf8");
      } catch {
        // continue
      }
    }
    return null;
  }

  function extractOrgxOpenclawUrl(configToml: string | null): string | null {
    if (!configToml) return null;
    const lines = configToml.split(/\r?\n/);
    let inTargetSection = false;
    for (const rawLine of lines) {
      const line = rawLine.trim();
      if (!line) continue;
      if (/^\[mcp_servers\.(?:"orgx-openclaw"|orgx-openclaw)\]\s*$/i.test(line)) {
        inTargetSection = true;
        continue;
      }
      if (inTargetSection && line.startsWith("[")) {
        break;
      }
      if (!inTargetSection) continue;
      const urlMatch = line.match(
        /^url\s*=\s*("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')\s*(?:#.*)?$/i
      );
      if (!urlMatch) continue;
      const token = (urlMatch[1] ?? "").trim();
      if (token.length < 2) continue;
      const quote = token[0];
      const unescaped = token
        .slice(1, -1)
        .replace(quote === '"' ? /\\"/g : /\\'/g, quote)
        .trim();
      const rawUrl = unescaped;
      if (rawUrl.length > 0) return rawUrl;
    }
    return null;
  }

  function prepareAutopilotCodexHome(): string | null {
    const configuredHome = (process.env.ORGX_AUTOPILOT_CODEX_HOME ?? "").trim();
    const preferredHome =
      configuredHome.length > 0
        ? configuredHome
        : join(getOrgxPluginConfigDir(), "codex-autopilot-home");
    const sourceHome = (process.env.CODEX_HOME ?? "").trim() || join(homedir(), ".codex");
    const sourceConfigCandidates = [
      join(sourceHome, "config.toml"),
      join(homedir(), ".codex", "config.toml"),
      join(homedir(), ".config", "codex", "config.toml"),
    ];

    const mcpModeRaw = (process.env.ORGX_AUTOPILOT_CODEX_MCP_MODE ?? "").trim().toLowerCase();
    const mcpMode = mcpModeRaw.length > 0 ? mcpModeRaw : "orgx-openclaw";
    const sourceConfig = readFirstExisting(sourceConfigCandidates);
    const extractedOrgxOpenclawUrl = extractOrgxOpenclawUrl(sourceConfig);
    const defaultOrgxOpenclawUrl =
      (process.env.ORGX_AUTOPILOT_ORGX_MCP_URL ?? "").trim() ||
      extractedOrgxOpenclawUrl ||
      "http://127.0.0.1:18789/orgx/mcp";

    const configLines: string[] = [
      "# Autogenerated by OrgX autopilot runtime. This isolates codex slices",
      "# from broken or noisy global MCP entries in ~/.codex/config.toml.",
      "",
    ];

    if (mcpMode === "none") {
      configLines.push("mcp_servers = {}", "");
    } else {
      configLines.push(
        '[mcp_servers."orgx-openclaw"]',
        `url = ${JSON.stringify(defaultOrgxOpenclawUrl)}`,
        ""
      );
    }

    const writeAutopilotHome = (targetHome: string): boolean => {
      try {
        mkdirSync(targetHome, { recursive: true, mode: 0o700 });
        try {
          chmodSync(targetHome, 0o700);
        } catch {
          // best effort
        }
      } catch {
        return false;
      }

      const sourceAuthPath = join(sourceHome, "auth.json");
      const targetAuthPath = join(targetHome, "auth.json");
      try {
        if (existsSync(sourceAuthPath)) {
          const authRaw = readFileSync(sourceAuthPath, "utf8");
          writeFileSync(targetAuthPath, authRaw, { encoding: "utf8", mode: 0o600 });
        }
      } catch {
        // best effort
      }

      try {
        writeFileSync(join(targetHome, "config.toml"), `${configLines.join("\n")}\n`, {
          encoding: "utf8",
          mode: 0o600,
        });
      } catch {
        return false;
      }
      return true;
    };

    if (writeAutopilotHome(preferredHome)) return preferredHome;

    // Hard fallback: use an ephemeral isolated CODEX_HOME so slices do not
    // inherit potentially broken global MCP config.
    try {
      const fallbackHome = mkdtempSync(join(tmpdir(), "orgx-autopilot-codex-home-"));
      if (writeAutopilotHome(fallbackHome)) return fallbackHome;
    } catch {
      // best effort
    }

    return null;
  }

  function ensurePrivateDirForFile(pathname: string): void {
    const dir = dirname(pathname);
    mkdirSync(dir, { recursive: true, mode: 0o700 });
    try {
      chmodSync(dir, 0o700);
    } catch {
      // best effort
    }
  }

  function createSafeAppendStream(pathname: string) {
    const stream = createWriteStream(pathname, { flags: "a" });
    stream.on("error", () => {
      // Best-effort logging only.
    });
    return stream;
  }

  function hasSliceOutput(pathname: string): boolean {
    try {
      if (!existsSync(pathname)) return false;
      const raw = readFileSync(pathname, "utf8");
      return raw.trim().length > 0;
    } catch {
      return false;
    }
  }

  function writeFallbackSliceOutput(input: {
    outputPath: string;
    runId: string;
    workstreamId?: string | undefined;
    workstreamTitle?: string | undefined;
    code: number | null;
    signal: NodeJS.Signals | null;
    reason: string;
  }): boolean {
    if (hasSliceOutput(input.outputPath)) return false;
    try {
      writeFileSync(
        input.outputPath,
        `${JSON.stringify(
          {
            status: "error",
            summary: `Worker exited without structured output (${input.reason}; code=${String(
              input.code
            )}, signal=${String(input.signal)}).`,
            workstream_id: input.workstreamId ?? "unknown",
            workstream_title: input.workstreamTitle ?? null,
            slice_id: input.runId,
          },
          null,
          2
        )}\n`,
        { encoding: "utf8", mode: 0o600 }
      );
      return true;
    } catch {
      return false;
    }
  }

  function sessionResumeEnabled(): boolean {
    const raw = (process.env.ORGX_AUTOPILOT_SESSION_RESUME ?? "").trim().toLowerCase();
    if (!raw) return false;
    return !(raw === "0" || raw === "false" || raw === "no" || raw === "off");
  }

  function spawnCodexSliceWorker(input: {
    runId: string;
    prompt: string;
    cwd: string;
    logPath: string;
    outputPath: string;
    outputSchemaPath?: string;
    env: Record<string, string | undefined>;
    resumeSessionId?: string | null;
  }): { pid: number | null } {
    ensurePrivateDirForFile(input.logPath);
    ensurePrivateDirForFile(input.outputPath);

    const workerKind = (
      input.env.ORGX_AUTOPILOT_WORKER_KIND ??
      process.env.ORGX_AUTOPILOT_WORKER_KIND ??
      ""
    )
      .trim()
      .toLowerCase();
    if (workerKind === "mock") {
      const scriptPath = resolve(
        dirname(deps.filename),
        "..",
        "..",
        "scripts",
        "mock-autopilot-slice-worker.mjs"
      );
      const logStream = createSafeAppendStream(input.logPath);
      const outStream = createSafeAppendStream(input.outputPath);
      logStream.write(`\n==== ${new Date().toISOString()} :: mock slice ${input.runId} ====\n`);

      const child = spawn("node", [scriptPath], {
        cwd: input.cwd,
        env: {
          ...process.env,
          ...input.env,
        },
        stdio: ["ignore", "pipe", "pipe"],
        // Keep the mock worker as a normal child so stdout/stderr capture is deterministic.
        detached: false,
      });
      deps.autoContinueSliceChildren.set(input.runId, child);
      try {
        logStream.write(
          `spawned pid=${String(child.pid ?? "")} stdout=${String(Boolean(child.stdout))} stderr=${String(
            Boolean(child.stderr)
          )}\n`
        );
      } catch {
        // ignore
      }

      child.stdout?.on("data", (chunk) => {
        try {
          logStream.write(chunk);
        } catch {
          // ignore
        }
        try {
          outStream.write(chunk);
        } catch {
          // ignore
        }
      });
      child.stderr?.on("data", (chunk) => {
        try {
          logStream.write(chunk);
        } catch {
          // ignore
        }
      });

      child.on("close", (code, signal) => {
        deps.autoContinueSliceChildren.delete(input.runId);
        const stamp = new Date().toISOString();
        const wroteFallback = writeFallbackSliceOutput({
          outputPath: input.outputPath,
          runId: input.runId,
          workstreamId: input.env.ORGX_WORKSTREAM_ID,
          workstreamTitle: input.env.ORGX_WORKSTREAM_TITLE,
          code,
          signal,
          reason: "mock worker close",
        });
        try {
          if (wroteFallback) {
            logStream.write(`fallback output synthesized at ${input.outputPath}\n`);
          }
          logStream.write(`\n==== ${stamp} :: exit code=${String(code)} signal=${String(signal)} ====\n`);
        } catch {
          // ignore
        }
        try {
          logStream.end();
        } catch {
          // ignore
        }
        try {
          outStream.end();
        } catch {
          // ignore
        }
      });
      child.on("error", (error) => {
        deps.autoContinueSliceChildren.delete(input.runId);
        const msg = deps.safeErrorMessage(error);
        try {
          logStream.write(`\nworker error: ${msg}\n`);
        } catch {
          // ignore
        }
        try {
          outStream.write(
            `${JSON.stringify(
              {
                status: "error",
                summary: `Worker spawn error: ${msg}`,
                workstream_id: input.env.ORGX_WORKSTREAM_ID ?? "unknown",
                workstream_title: input.env.ORGX_WORKSTREAM_TITLE ?? null,
                slice_id: input.runId,
              },
              null,
              2
            )}\n`
          );
        } catch {
          // ignore
        }
      });

      return { pid: child.pid ?? null };
    }

    if (workerKind === "claude-code" || workerKind === "claude_code") {
      const hasArgFlag = (args: string[], flag: string): boolean =>
        args.includes(flag) || args.some((arg) => typeof arg === "string" && arg.startsWith(`${flag}=`));
      const readArgValue = (args: string[], flag: string): string | null => {
        const inline = args.find((arg) => typeof arg === "string" && arg.startsWith(`${flag}=`));
        if (inline) return inline.slice(flag.length + 1).trim() || null;
        const index = args.indexOf(flag);
        const next = index >= 0 ? args[index + 1] : null;
        return typeof next === "string" && next.trim().length > 0 ? next.trim() : null;
      };

      const claudeBin = (process.env.ORGX_CLAUDE_CODE_BIN ?? "").trim() || "claude";
      const rawArgs = (process.env.ORGX_CLAUDE_CODE_ARGS ?? "").trim();
      const args = rawArgs.length > 0 ? rawArgs.split(/\s+/).filter(Boolean) : [];
      const hasPrint = hasArgFlag(args, "--print") || args.includes("-p");
      const hasOutputFormat = hasArgFlag(args, "--output-format");
      const hasJsonSchema = hasArgFlag(args, "--json-schema");
      const hasNoSessionPersistence = hasArgFlag(args, "--no-session-persistence");
      const hasPermissionMode = hasArgFlag(args, "--permission-mode");
      const hasDangerousSkipPermissions = hasArgFlag(args, "--dangerously-skip-permissions");
      const hasAllowDangerousSkipPermissions = hasArgFlag(args, "--allow-dangerously-skip-permissions");
      const explicitOutputFormat = readArgValue(args, "--output-format");
      const explicitJsonSchemaArg = readArgValue(args, "--json-schema");
      const explicitPermissionMode = readArgValue(args, "--permission-mode");
      let schemaArg: string | null = null;
      if (input.outputSchemaPath && !hasJsonSchema) {
        try {
          const schemaRaw = readFileSync(input.outputSchemaPath, "utf8").trim();
          if (schemaRaw.length > 0) schemaArg = schemaRaw;
        } catch {
          schemaArg = null;
        }
      }
      const claudeExtraArgs: string[] = [];
      if (!hasPrint) claudeExtraArgs.push("--print");
      if (!hasOutputFormat) claudeExtraArgs.push("--output-format", "json");
      // Session resume: when resumeSessionId is provided, use --resume and skip --no-session-persistence.
      // When feature is enabled but no resume, omit --no-session-persistence to persist for future resume.
      const resumeId = typeof input.resumeSessionId === "string" ? input.resumeSessionId.trim() : "";
      if (resumeId) {
        claudeExtraArgs.push("--resume", resumeId);
      } else if (!sessionResumeEnabled() && !hasNoSessionPersistence) {
        claudeExtraArgs.push("--no-session-persistence");
      }
      if (!hasPermissionMode) claudeExtraArgs.push("--permission-mode", "bypassPermissions");
      if (!hasDangerousSkipPermissions && !hasAllowDangerousSkipPermissions) {
        claudeExtraArgs.push("--dangerously-skip-permissions");
      }
      if (schemaArg) claudeExtraArgs.push("--json-schema", schemaArg);

      const logStream = createSafeAppendStream(input.logPath);
      const outStream = createSafeAppendStream(input.outputPath);
      logStream.write(`\n==== ${new Date().toISOString()} :: claude slice ${input.runId} ====\n`);
      logStream.write(`claude_bin: ${claudeBin}\n`);
      if (claudeExtraArgs.length > 0) {
        const claudeArgsForLog = claudeExtraArgs.map((arg) => {
          if (schemaArg && arg === schemaArg) return "<json-schema>";
          return arg.length > 160 ? `${arg.slice(0, 157)}...` : arg;
        });
        logStream.write(`claude_args_injected: ${claudeArgsForLog.join(" ")}\n`);
      }
      if (schemaArg && input.outputSchemaPath) {
        logStream.write(`claude_json_schema: ${input.outputSchemaPath}\n`);
      } else if (hasJsonSchema) {
        logStream.write(`claude_json_schema: ${explicitJsonSchemaArg ?? "provided-via-args"}\n`);
      } else if (input.outputSchemaPath && !hasJsonSchema) {
        logStream.write(`claude_json_schema: unavailable (${input.outputSchemaPath})\n`);
      }
      logStream.write(`claude_output_format: ${hasOutputFormat ? explicitOutputFormat ?? "provided" : "json"}\n`);
      logStream.write(
        `claude_permission_mode: ${hasPermissionMode ? explicitPermissionMode ?? "provided" : "bypassPermissions"}\n`
      );
      logStream.write(
        `claude_skip_permissions: ${hasDangerousSkipPermissions || hasAllowDangerousSkipPermissions ? "provided" : "dangerously-skip-permissions"}\n`
      );

      const childEnv: Record<string, string | undefined> = {
        ...process.env,
        ...deps.resolveByokEnvOverrides(),
        ...input.env,
      };
      if (claudeBin.includes(sep)) {
        const binDir = dirname(claudeBin);
        childEnv.PATH = childEnv.PATH ? `${binDir}:${childEnv.PATH}` : binDir;
      }

      // Force non-interactive structured output by default for parity with codex output-schema mode.
      // If callers already pass explicit print/output/schema flags, we preserve their args unchanged.
      const child = spawn(claudeBin, [...args, ...claudeExtraArgs, input.prompt], {
        cwd: input.cwd,
        env: childEnv,
        stdio: ["ignore", "pipe", "pipe"],
        detached: true,
      });
      deps.autoContinueSliceChildren.set(input.runId, child);

      child.stdout?.on("data", (chunk) => {
        try {
          logStream.write(chunk);
        } catch {
          // ignore
        }
        try {
          outStream.write(chunk);
        } catch {
          // ignore
        }
      });
      child.stderr?.on("data", (chunk) => {
        try {
          logStream.write(chunk);
        } catch {
          // ignore
        }
      });

      child.on("close", (code, signal) => {
        deps.autoContinueSliceChildren.delete(input.runId);
        const stamp = new Date().toISOString();
        const wroteFallback = writeFallbackSliceOutput({
          outputPath: input.outputPath,
          runId: input.runId,
          workstreamId: input.env.ORGX_WORKSTREAM_ID,
          workstreamTitle: input.env.ORGX_WORKSTREAM_TITLE,
          code,
          signal,
          reason: "claude worker close",
        });
        try {
          if (wroteFallback) {
            logStream.write(`fallback output synthesized at ${input.outputPath}\n`);
          }
          logStream.write(`\n==== ${stamp} :: exit code=${String(code)} signal=${String(signal)} ====\n`);
        } catch {
          // ignore
        }
        try {
          logStream.end();
        } catch {
          // ignore
        }
        try {
          outStream.end();
        } catch {
          // ignore
        }
      });

      child.on("error", (error) => {
        deps.autoContinueSliceChildren.delete(input.runId);
        const msg = deps.safeErrorMessage(error);
        try {
          logStream.write(`\nworker error: ${msg}\n`);
        } catch {
          // ignore
        }
        try {
          outStream.write(
            `${JSON.stringify(
              {
                status: "error",
                summary: `Worker spawn error: ${msg}`,
                workstream_id: input.env.ORGX_WORKSTREAM_ID ?? "unknown",
                workstream_title: input.env.ORGX_WORKSTREAM_TITLE ?? null,
                slice_id: input.runId,
              },
              null,
              2
            )}\n`
          );
        } catch {
          // ignore
        }
      });

      child.unref();
      return { pid: child.pid ?? null };
    }

    const codexInfo = deps.resolveCodexBinInfo();
    const codexBin = codexInfo.bin;
    const codexResumeId = typeof input.resumeSessionId === "string" ? input.resumeSessionId.trim() : "";

    // Session resume: use "resume <id>" subcommand instead of "exec --ephemeral"
    // When feature enabled but no resume ID: omit --ephemeral to persist for future resume
    let rawArgs: string;
    let defaultArgs: string[];
    if (codexResumeId) {
      rawArgs = "";
      defaultArgs = ["resume", codexResumeId, "--full-auto", "--skip-git-repo-check"];
    } else {
      rawArgs = (process.env.ORGX_CODEX_ARGS ?? "").trim();
      const featureEnabled = sessionResumeEnabled();
      defaultArgs = featureEnabled
        ? ["exec", "--full-auto", "--skip-git-repo-check"]
        : ["exec", "--ephemeral", "--full-auto", "--skip-git-repo-check"];
    }
    const normalizedArgs = normalizeCodexArgs(
      rawArgs.length > 0
        ? rawArgs.split(/\s+/).filter(Boolean)
        : defaultArgs
    );
    const args = hasExplicitCodexSubcommand(normalizedArgs)
      ? normalizedArgs
      : ["exec", ...normalizedArgs];

    const extraArgs: string[] = [];

    const logStream = createSafeAppendStream(input.logPath);
    logStream.write(`\n==== ${new Date().toISOString()} :: slice ${input.runId} ====\n`);
    logStream.write(
      `codex_bin: ${codexBin}${codexInfo.versionString ? ` (${codexInfo.versionString})` : ""}\n`
    );

    const childEnv: Record<string, string | undefined> = {
      ...process.env,
      ...deps.resolveByokEnvOverrides(),
      ...input.env,
    };
    const shouldIsolateCodexHome = envFlag("ORGX_AUTOPILOT_ISOLATE_CODEX_HOME", true);
    const autopilotCodexHome = prepareAutopilotCodexHome();
    if (autopilotCodexHome) {
      childEnv.CODEX_HOME = autopilotCodexHome;
      logStream.write(
        shouldIsolateCodexHome
          ? `codex_home: ${autopilotCodexHome}\n`
          : `codex_home: ${autopilotCodexHome} (forced-safe override while ORGX_AUTOPILOT_ISOLATE_CODEX_HOME=false)\n`
      );
    } else if (shouldIsolateCodexHome) {
      delete childEnv.CODEX_HOME;
      logStream.write("codex_home: isolation unavailable (default lookup)\n");
    } else {
      logStream.write("codex_home: forced-safe override unavailable (inheriting global CODEX_HOME)\n");
    }
    if (codexBin.includes(sep)) {
      const binDir = dirname(codexBin);
      childEnv.PATH = childEnv.PATH ? `${binDir}:${childEnv.PATH}` : binDir;
    }

    const hasOutputLastMessage =
      args.includes("--output-last-message") ||
      args.some((arg) => typeof arg === "string" && arg.startsWith("--output-last-message="));
    const outputArgs = hasOutputLastMessage
      ? []
      : ["--output-last-message", input.outputPath];
    const hasOutputSchema =
      args.includes("--output-schema") ||
      args.some((arg) => typeof arg === "string" && arg.startsWith("--output-schema="));
    const outputSchemaArgs =
      input.outputSchemaPath && !hasOutputSchema
        ? ["--output-schema", input.outputSchemaPath]
        : [];
    if (outputSchemaArgs.length > 0) {
      logStream.write(`output_schema: ${input.outputSchemaPath}\n`);
    }

    const child = spawn(
      codexBin,
      [...args, ...extraArgs, ...outputArgs, ...outputSchemaArgs, input.prompt],
      {
      cwd: input.cwd,
      env: childEnv,
      stdio: ["ignore", "pipe", "pipe"],
      detached: true,
      }
    );
    deps.autoContinueSliceChildren.set(input.runId, child);

    child.stdout?.on("data", (chunk) => {
      try {
        logStream.write(chunk);
      } catch {
        // ignore
      }
    });
    child.stderr?.on("data", (chunk) => {
      try {
        logStream.write(chunk);
      } catch {
        // ignore
      }
    });

    child.on("close", (code, signal) => {
      deps.autoContinueSliceChildren.delete(input.runId);
      const stamp = new Date().toISOString();
      const wroteFallback = writeFallbackSliceOutput({
        outputPath: input.outputPath,
        runId: input.runId,
        workstreamId: input.env.ORGX_WORKSTREAM_ID,
        workstreamTitle: input.env.ORGX_WORKSTREAM_TITLE,
        code,
        signal,
        reason: "codex worker close",
      });
      try {
        if (wroteFallback) {
          logStream.write(`fallback output synthesized at ${input.outputPath}\n`);
        }
        logStream.write(`\n==== ${stamp} :: exit code=${String(code)} signal=${String(signal)} ====\n`);
      } catch {
        // ignore
      }
      try {
        logStream.end();
      } catch {
        // ignore
      }
    });
    child.on("error", (error) => {
      deps.autoContinueSliceChildren.delete(input.runId);
      const msg = deps.safeErrorMessage(error);
      try {
        logStream.write(`\nworker error: ${msg}\n`);
      } catch {
        // ignore
      }
      try {
        writeFileSync(
          input.outputPath,
          `${JSON.stringify(
            {
              status: "error",
              summary: `Worker spawn error: ${msg}`,
              workstream_id: input.env.ORGX_WORKSTREAM_ID ?? "unknown",
              workstream_title: input.env.ORGX_WORKSTREAM_TITLE ?? null,
              slice_id: input.runId,
            },
            null,
            2
          )}\n`,
          { encoding: "utf8" }
        );
      } catch {
        // ignore
      }
    });

    child.unref();
    return { pid: child.pid ?? null };
  }

  function writeRuntimeEvent(input: {
    sourceClient: RuntimeSourceClient;
    event: RuntimeHookPayload["event"];
    runId: string;
    initiativeId: string;
    workstreamId: string | null;
    taskId: string | null;
    agentId: string | null;
    agentName: string | null;
    phase: string | null;
    message?: string | null;
    progressPct?: number | null;
    metadata?: Record<string, unknown> | null;
    timestamp?: string | null;
  }): RuntimeInstanceRecord {
    const instance = deps.upsertRuntimeInstanceFromHook({
      source_client: input.sourceClient,
      event: input.event ?? null,
      run_id: input.runId,
      correlation_id: input.runId,
      initiative_id: input.initiativeId,
      workstream_id: input.workstreamId,
      task_id: input.taskId,
      agent_id: input.agentId,
      agent_name: input.agentName,
      phase: input.phase,
      progress_pct: input.progressPct ?? null,
      message: input.message ?? null,
      metadata: input.metadata ?? null,
      timestamp: input.timestamp ?? new Date().toISOString(),
    });
    // Make runtime updates feel instantaneous (don't wait for the 15s staleness timer).
    deps.broadcastRuntimeSse("runtime.updated", instance);
    deps.clearSnapshotResponseCache();
    return instance;
  }

  return {
    spawnCodexSliceWorker,
    writeRuntimeEvent,
  };
}
